version: '3'
services:
  ollama:
    hostname: ollama
    container_name: ollama
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_models:/root/custom_models
    networks:
      - net
  flowise:
      hostname: flowise
      container_name: flowise
      image: flowiseai/flowise
      restart: always
      environment:
        - PORT=4505
        - FLOWISE_USERNAME=admin
        - FLOWISE_PASSWORD=admin
        - LOG_PATH=/var/flowiselog
        - LOG_LEVEL=verbose
      ports:
        - '4505:4505'
      volumes:
        - ~/.flowise:/root/.flowise
        - ./custom_data:/var/custom_data
      command: /bin/sh -c "sleep 3; flowise start"
      networks:
        - net 
  qdrant:
    hostname: qdrant
    container_name: qdrant
    restart: always
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
       - net

volumes:
  ollama_data:
    driver: local
  qdrant_data:

networks:
  net:
    driver: bridge