version: '3'
services:
  ollama:
    hostname: ollama
    container_name: ollama
    build:
      context: ./ollama
      dockerfile: Dockerfile
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_models:/root/custom_models
    networks:
      - net
  flowise:
      hostname: flowise
      container_name: flowise
      image: flowiseai/flowise
      restart: always
      environment:
        - PORT=4505
        - FLOWISE_USERNAME=admin
        - FLOWISE_PASSWORD=admin
      ports:
        - '4505:4505'
      volumes:
        - ~/.flowise:/root/.flowise
      command: /bin/sh -c "sleep 3; flowise start"
      networks:
        - net
  weaviate:
    hostname: weaviate
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.23.3
    ports:
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'weaviate'
    networks:
      - net
     
volumes:
  ollama_data:
    driver: local
  weaviate_data:

networks:
  net:
    driver: bridge